const PLAY = "PLAY"
const PAUSE = "PAUSE"
const SET_ACTIVE = "SET_ACTIVE"
const SET_DURATION = "SET_DURATION"
const SET_CURRENT_TIME = "SET_CURRENT_TIME"
const SET_VOLUME = "SET_VOLUME"

export const PlayerActionTypes = {
    PLAY,
    PAUSE,
    SET_ACTIVE,
    SET_DURATION,
    SET_CURRENT_TIME,
    SET_VOLUME
}

